doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            order_status: AppBundle\Doctrine\DBAL\Types\OrderStatus
            contact_type: AppBundle\Doctrine\DBAL\Types\ContactType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy:             doctrine.orm.naming_strategy.underscore
        auto_mapping:                true

doctrine_migrations:
    dir_name:   "%kernel.root_dir%/migrations"
    namespace:  Migrations
    table_name: migrations
    name:       Application Migrations

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
